version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    groups:
      frameworks:
        patterns:
          - "fastapi"
          - "httpx"
          - "starlette"
          - "uvicorn*"
      redis:
        patterns:
          - "redis"
      testing-and-build:
        patterns:
          - "build"
          - "pytest"
          - "pytest-asyncio"
          - "twine"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
